/*
 * This source file was generated by the Gradle 'init' task
 */
package io.onicodes;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class AppTest {
    @Test public void contextLoads() {
        assert(true);
    }
}
